default:
  interruptible: true
  image: eclipse-temurin:21-jdk-alpine

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: $CI_COMMIT_TAG

stages:
  - build
  - test
  - deploy
  - destroy

build_backend:
  stage: build
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:27.3.1-dind
  script:
    - echo "Building battleship backend"
    - chmod +x gradlew
    - cd ./battleship-backend
    - ../gradlew clean bootBuildImage
    - cd ..
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'ci-cd'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


build_frontend:
  stage: build
  before_script:
    - set -e
    - apk add --no-cache docker
    - echo "Logging into Azure"
    - docker login $GAME_REGISTRY_USERNAME.azurecr.io -u $GAME_REGISTRY_USERNAME -p $GAME_REGISTRY_PASSWORD
  script:
    - echo "Building and tagging game frontend project"
    - docker build
      --build-arg VITE_BS_BACKEND_URL=$GAME_BACKEND_URL
      -t $GAME_REGISTRY_USERNAME.azurecr.io/bandit-frontend-dev:latest
      .
    - echo "Publishing frontend dev image to Azure"
    - docker push $GAME_REGISTRY_USERNAME.azurecr.io/bandit-frontend-dev:latest
  services:
    - docker:27.3.1-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'ci-cd'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


