@lobby_id = e5b12614-02fc-4438-ba54-6f53ae64f0ac

### POST to ready up for player 1
POST http://localhost:9175/api/lobby/{{lobby_id}}/ready
Accept: application/json
Content-Type: application/json

{
    "playerId": "cd281b11-e41e-4f12-93c8-1e9a8bf7403c"
}

### POST to ready up for player 2
POST http://localhost:9175/api/lobby/{{lobby_id}}/ready
Accept: application/json
Content-Type: application/json

{
    "playerId": "6ca3863d-d8db-4588-b799-704fdb267814"
}

### POST for player 1 to arrange ships
POST http://localhost:9175/api/arrange_ships
Accept: application/json
Content-Type: application/json

{
    "identity": {
        "lobbyId":"{{lobby_id}}",
        "playerId":"cd281b11-e41e-4f12-93c8-1e9a8bf7403c"
    },
    "arrangedShips":[
        {"type":"CARRIER","placement":{"col":1,"row":1},"isVertical":false},
        {"type":"BATTLESHIP","placement":{"col":8,"row":5},"isVertical":true},
        {"type":"CRUISER","placement":{"col":1,"row":4},"isVertical":false},
        {"type":"SUBMARINE","placement":{"col":4,"row":6},"isVertical":true},
        {"type":"DESTROYER","placement":{"col":6,"row":3},"isVertical":false}
    ]
}

### POST for player 2 to arrange ships
POST http://localhost:9175/api/arrange_ships
Accept: application/json
Content-Type: application/json

{
    "identity": {
        "lobbyId":"{{lobby_id}}",
        "playerId":"6ca3863d-d8db-4588-b799-704fdb267814"
    },
    "arrangedShips": [
        {"type":"CARRIER","placement":{"col":1,"row":0},"isVertical":false},
        {"type":"BATTLESHIP","placement":{"col":1,"row":2},"isVertical":false},
        {"type":"CRUISER","placement":{"col":5,"row":5},"isVertical":false},
        {"type":"SUBMARINE","placement":{"col":1,"row":3},"isVertical":true},
        {"type":"DESTROYER","placement":{"col":3,"row":7},"isVertical":true}
    ]
}

### GET lobby information
GET http://localhost:9175/api/lobby/{{lobby_id}}
Accept: application/json

### GET to get the battle status for the player
GET http://localhost:9175/api/battle/status?playerId=cd281b11-e41e-4f12-93c8-1e9a8bf7403c&lobbyId={{lobby_id}}
Accept: application/json

### POST to shoot as player 1
POST http://localhost:9175/api/battle/shoot
Accept: application/json
Content-Type: application/json

{
    "identity": {
        "playerId": "cd281b11-e41e-4f12-93c8-1e9a8bf7403c",
        "lobbyId": "{{lobby_id}}"
    },
    "column": 0,
    "row": 0
}

### POST to shoot as player 2
POST http://localhost:9175/api/battle/shoot
Accept: application/json
Content-Type: application/json

{
    "identity": {
        "playerId": "6ca3863d-d8db-4588-b799-704fdb267814",
        "lobbyId": "{{lobby_id}}"
    },
    "column": 2,
    "row": 0
}
